version: '3.9'

services:
  backend:
    build:
    container_name: mern-backend
    ports: -"5000:5000"
    env_file:
      - ..variables.env
    volumes:
      - backend-data:/app
    depends_on: -mongo
    networks: -mern-network

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports: -"3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:6
    container_name: mern-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

volumes:
  backend-data:
  mongo-data:

networks:
  mern-network:
    driver: bridge
